
backend:
  name: github
  repo: areensalam14-cmyk/anna-gull
  branch: main

media_folder: "images"
public_folder: "/anna-gull/images"

collections:
  - name: "bouquets"
    label: "Bouquets"
    folder: "_bouquets"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - label: "Bouquet Name"
        name: "title"
        widget: "string"
      - label: "Price (IQD)"
        name: "price"
        widget: "number"
      - label: "Photo"
        name: "image"
        widget: "image"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
